language: ruby
sudo: false
cache: bundler
rvm:
- 2.1.2
branches:
  except:
    - master
    - archived_octopress

install:
  - gem install bundler
  - bundle install --with=distribution

script:
  - rake build
  - '[ ! -z $DANGER_GITHUB_API_TOKEN ] && bundle exec danger || echo "Skipping Danger for External Contributor"'

after_success: rake deploy:travis
