language: ruby
sudo: false
cache: bundler
rvm:
- 2.1.2
env:
  global:
    secure: U6P/itvYt53J4zwddpwf+kyVMayXpDwSIYho1s6h1hGAQ8H6YGfh0jjEO1wIk6bL2xNTknNGArnFVgPl9cslGx7lz5ouG06CAm8siYpzzw29teOS1FIAN0yldCDPDLcjMg7pdWcJNulPbpQVC/K9V6DShp99o/hrWfHCQ+bAJeg=
before_install:
- echo "machine github.com login $GH_TOKEN" > ~/.netrc
- chmod 600 ~/.netrc
script:
- rake build
after_success:
- rake deploy:travis
