language: ruby
sudo: false
cache: bundler
rvm:
- 2.1.2
branches:
  except:
    - master
    - archived_octopress
env:
  global:
    secure: U6P/itvYt53J4zwddpwf+kyVMayXpDwSIYho1s6h1hGAQ8H6YGfh0jjEO1wIk6bL2xNTknNGArnFVgPl9cslGx7lz5ouG06CAm8siYpzzw29teOS1FIAN0yldCDPDLcjMg7pdWcJNulPbpQVC/K9V6DShp99o/hrWfHCQ+bAJeg=
script:
  - rake build
  - if [ "$DANGER_GITHUB_API_TOKEN" = "" ]; then; echo "Skipping Danger for External Contributor"; else; bundle exec danger; fi
after_success: rake deploy:travis
